[package]
name = "leonardo/factory-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
matter = "matter-ecs/matter@0.9.0-beta.0"
plasma = "matter-ecs/plasma@0.4.2"
signal = "sleitnick/signal@2.0.3"
ParallelWorker = "maximumadhd/parallel-worker@1.0.0"